/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_ihk_tcp_cardreader_usb_TCPUSB */

#ifndef _Included_dk_ihk_tcp_cardreader_usb_TCPUSB
#define _Included_dk_ihk_tcp_cardreader_usb_TCPUSB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_ihk_tcp_cardreader_usb_TCPUSB
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_ihk_tcp_cardreader_usb_TCPUSB_init
  (JNIEnv *, jobject);

/*
 * Class:     dk_ihk_tcp_cardreader_usb_TCPUSB
 * Method:    connect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dk_ihk_tcp_cardreader_usb_TCPUSB_connect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dk_ihk_tcp_cardreader_usb_TCPUSB
 * Method:    disconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_ihk_tcp_cardreader_usb_TCPUSB_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     dk_ihk_tcp_cardreader_usb_TCPUSB
 * Method:    send
 * Signature: (I[S)I
 */
JNIEXPORT jint JNICALL Java_dk_ihk_tcp_cardreader_usb_TCPUSB_send
  (JNIEnv *, jobject, jint, jshortArray);

/*
 * Class:     dk_ihk_tcp_cardreader_usb_TCPUSB
 * Method:    interrupt
 * Signature: ([S)I
 */
JNIEXPORT jint JNICALL Java_dk_ihk_tcp_cardreader_usb_TCPUSB_interrupt
  (JNIEnv *, jobject, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
